Add support to show current date and time
justjanne/powerline-go pull request #321
Opened 2021-07-23 10:24 UTC by flybyray

Fixes #238

This allows to give a time layout as argument. See details [Time.Format](https://pkg.go.dev/time#Time.Format)

```shell
function _update_ps1() {
    PS1="$(powerline-go -error $? -jobs $(jobs -p | wc -l) -newline -time '06-02-01 15:04:05' -modules time,cwd,exit,git,hg,host,jobs,perms,root,ssh,user,venv )"
}
```

If no argument given to time option it will use the default before this pull request.

2021-09-15 16:21 UTC, justjanne requested changes

2021-09-15 16:21 UTC, justjanne commented on args.go
> +		comments("The elapsed clock-time of the previous command")),
Please correct the description of this flag

2021-12-12 11:20 UTC, embeddedc commented
Could be merged now?

2022-02-17 19:16 UTC, merged

2022-10-24 15:55 UTC, vitaly-zdanevich commented
And how to enable this?

2023-01-05 14:49 UTC, embeddedc commented
> And how to enable this?

`-modules time`