Increased the performance of GCP segment
justjanne/powerline-go pull request #331
Opened 2021-10-01 00:39 UTC by caleb-artifact

Reduced the amount of time it takes to get the Google Cloud Project by attempting to read config files directly, and falling back to gcloud only if we experience an error.

2021-10-01 20:47 UTC, justjanne requested changes

2021-10-01 20:47 UTC, justjanne commented on segment-gcp.go
> +		//return []pwl.Segment{}
```suggestion
```

2021-10-01 20:48 UTC, justjanne commented
I’ll further look into it this weekend

2022-03-20 21:19 UTC, caleb-artifact commented
I updated the commit with you suggestion, wondering if you have had time to review the change?

2022-04-20 17:29 UTC, merged